# Generated by Django 5.1.1 on 2024-09-16 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('start_latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('start_longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('end_location', models.CharField(max_length=255)),
                ('end_latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('end_longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('departure_time', models.DateTimeField()),
                ('total_seats', models.IntegerField(default=1)),
                ('booked_seats', models.IntegerField(default=0)),
                ('status', models.CharField(default='Available', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
