# Generated by Django 5.1.4 on 2024-12-08 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10)),
                ('max_passengers', models.PositiveIntegerField(default=4)),
                ('start_latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('start_longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('end_latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('end_longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_as_driver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled'), ('TERMINATED', 'Terminated'), ('COMPLETED', 'Completed')], default='CONFIRMED', max_length=10)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='sajan.ride')),
            ],
        ),
    ]
