# Generated by Django 5.1.1 on 2024-09-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sajan', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='end_latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='ride',
            name='end_longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='ride',
            name='start_latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='ride',
            name='start_longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled'), ('TERMINATED', 'Terminated'), ('COMPLETED', 'Completed')], default='CONFIRMED', max_length=10),
        ),
    ]
