# Generated by Django 5.1.1 on 2024-11-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sajan', '0003_ride_end_latitude_ride_end_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='updated_at',
        ),
    ]
