# Generated by Django 5.1.1 on 2024-11-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sajan', '0004_remove_ride_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
